name: Docker Image CI

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 0 14,28 * *'

jobs:

  build:
    strategy:
      matrix:
        ubuntu_release: ["20.04", "20.10"]
        rpy2_version: ["master", "v3.4.5"]
    env: 
      RPY2_VERSION: master
      LATEST_UBUNTU: "20.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build base image
      run: |
        docker build base \
          --tag babessell/base-ubuntu:"${{ matrix.rpy2_version }}"-"${{ matrix.ubuntu_release }}" \
          --build-arg RPY2_VERSION="${{ matrix.rpy2_version }}" \
          --build-arg UBUNTU_RELEASE="${{ matrix.ubuntu_release }}"
    - name: Push base image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        IMAGE_TAG=babessell/base-ubuntu:"${{ matrix.rpy2_version }}"-"${{ matrix.ubuntu_release }}"
        docker tag "${IMAGE_TAG}" "${IMAGE_TAG}"
        docker push "${IMAGE_TAG}"
        if [ "${{ matrix.ubuntu_release }}" == "${LATEST_UBUNTU}" ]; then
          docker tag "${IMAGE_TAG}" rpy2/base-ubuntu:latest
          docker push babessell/base-ubuntu:latest
        fi
   
